spring.application.name=Cloud.Four

spring.datasource.url=jdbc:postgresql://localhost:5432/dbnotes
spring.datasource.username=postgres
spring.datasource.password=nala123

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.date-format=yyyy-MM-dd'T'HH:mm:ss
