spring.application.name=Cloud.Four

spring.datasource.url=jdbc:postgresql://localhost:5432/dbnotes
spring.datasource.username=postgres
spring.datasource.password=1234
spring.hibernate.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update